version: "3"
   
services:
  app:
    container_name: flask_container
    build:
      context: .
      dockerfile: Dockerfile
    command:  python index.py
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"
    restart: always
